neo-project/neo-vm

- src/neo-vm/ExecutionEngine.cs
- src/neo-vm/OpCode.cs
- src/neo-vm/StackItem.cs
- src/neo-vm/Types/Array.cs
- src/neo-vm/Types/Map.cs
- src/neo-vm/neo-vm.csproj
Implemented #27 (partially):
1. Add new type `Map`.
2. Add new opcodes: `NEWMAP`, `HASKEY`, `KEYS`, `VALUES`.
3. Modify the opcodes `ARRAYSIZE`, `PICKITEM`, `SETITEM`, `REMOVE` to support map.
close #27
> add `Map` to NeoVM

- src/neo-vm/ExecutionContext.cs
- src/neo-vm/ExecutionEngine.cs
- src/neo-vm/HashComparer.cs
- src/neo-vm/InteropService.cs
- src/neo-vm/OpCode.cs
- src/neo-vm/RandomAccessStack.cs
- src/neo-vm/neo-vm.csproj
Implement NEP-8: Stack Isolation
https://github.com/neo-project/proposals/pull/22
Close #35
> Stack Isolation

- src/neo-vm/Helper.cs
- src/neo-vm/InteropService.cs
An extra dictionary from string to uint will help complementing interop function accesses. That will help implementing it on Neo: https://github.com/neo-project/neo/issues/264
This is a small continuation of this PR: https://github.com/neo-project/neo-vm/pull/61
> Added extra dictionary mapping from string -> uint

- src/neo-vm/ExecutionEngine.cs
- src/neo-vm/Helper.cs
I believe ReadVarBytes is not necessary for NeoVM, and it's even misleading now that its limits on NeoVM (int max = 0X7fffffc7) differ from Neo limits of the "same" function (int max = 0x1000000).
ReadVarInt was also duplicated, so it was removed too. 
A new function called SafeReadBytes (inspired by @shargon discussion https://github.com/neo-project/neo/pull/511) was added, and it can be reused inside Neo project if necessary.
> Add SafeReadBytes from VM

- src/neo-vm/ExecutionEngine.cs
https://github.com/neo-project/neo-vm/blob/41724f6276bf8d21787c979f063fe8b79c0115b3/src/neo-vm/ExecutionEngine.cs#L1312-L1323
A negative `count` does not fail until it hits the for-loop on line 1323 which then seems to throw an exception into the `catch` here
https://github.com/neo-project/neo-vm/blob/41724f6276bf8d21787c979f063fe8b79c0115b3/src/neo-vm/ExecutionEngine.cs#L226-L233
We can potentially save quite some cycles if we do not have to execute `CheckArraySize` but exit early via the proposed addition.  The same holds true for `NEWSTRUCT`
> Check for negative count in NEWARRAY/NEWSTRUCT

- src/neo-vm/ExecutionEngine.cs
These methods are added for doing some additional verifications in sub class. Such as `gas` check.
> Add `PreExecuteInstruction()` and `PostExecuteInstruction()` virtual methods

- src/neo-vm/ExecutionEngine.cs
Prevent to compute `CurrentContext.ScriptHash` if there are none break points, this allow to use ExecutionEngine without ICrypto for small smart contracts (Benchmarks)
> Small optimization

- .travis.yml
- README.md
- tests/neo-vm.Tests/UtStruct.cs
- tests/neo-vm.Tests/UtVMJson.cs
- tests/neo-vm.Tests/neo-vm.Tests.csproj
With these changes we can begin to include coverage in all pull requests, it is very useful to deny pull requests that decrease coverage, it could also help to see which areas of the code don't have unit tests yet, and we can focus more on this.
It require few more steps from your side @erikzhang 
First we need to define the secure environment token for coverals (in travis settings):
We can get this token here, but first you need to give access to the repository to https://coveralls.io (like travis)
With this, we should be able (if all of this changes are ok) to see comments like this (https://github.com/CityOfZion/neo-sharp/pull/560#issuecomment-445799994) in every pull request, and be able to see the areas without tests, and we can improve the coverage to 100%!
*PD: Maybe I forgot a …
> Add Coverals to neo-vm

- tests/neo-vm.Tests/Helpers/RandomHelper.cs
- tests/neo-vm.Tests/UtScriptBuilder.cs
`EmitSysCall` must push the api hash instead of the string
@erikzhang what do you prefer. I can update this Pull Request or made another one
> ScriptBuilder unit tests

- src/neo-vm/ScriptBuilder.cs
- tests/neo-vm.Tests/UtScriptBuilder.cs
With this change we can build using the last version of `SYSCALL`
> Allow to compress syscalls api methods

- tests/neo-vm.Tests/Extensions/ByteArrayExtensions.cs
- tests/neo-vm.Tests/Tests/OpCodes/Control/APPCALL.json
- tests/neo-vm.Tests/Tests/OpCodes/Control/TAILCALL.json
Also was Removed one unused method
> APPCALL and TAILCALL unit tests

- src/neo-vm/Debugger.cs
- tests/neo-vm.Tests/UtDebugger.cs
If you place a breakpoint within a method and call StepOver, you will never reach the breakpoints, this pull request fix the issue
> Fix breakpoints on StepOver and StepOut

- src/neo-vm/ExecutionEngine.cs
In NEO 3.0, we need to keep the restrictions on `NUMEQUAL` and `NUMNOTEQUAL`. So, from now there will be two master branches: `master` is for NEO 3.0, and `master-2.x` is for NEO 2.x.
Closes #123
> Revert the restrictions of NUMEQUAL and NUMNOTEQUAL

- src/neo-vm/ExecutionEngine.cs
I think the old implementation of `CALL_I` is incorrect. But the old contract has been running correctly on the wrong implementation, so a compatible version must be provided.
@hal0x2328, can you review this fix?
Closes #130
Closes neo-project/neo-cli#343
> Fixes CALL_I

- src/neo-vm/ExecutionContext.cs
- src/neo-vm/ExecutionEngine.cs
- src/neo-vm/neo-vm.csproj
- tests/neo-vm.Tests/Types/InteropService.cs
This reverts commit 38c5dc0c63c70703f9d49970c2401e565972c3af.
> Revert "Fixes GetEntryScriptHash and GetCallingScriptHash (2.x) (#138)"

- src/neo-vm/Types/Boolean.cs
- tests/neo-vm.Tests/Tests/OpCodes/Splice/SIZE.json
Closes https://github.com/neo-project/neo-vm/issues/129
a Boolean StackItem in either `false` or `true` state should always return at least 1 byte for `GetByteArray()`. This is the default behaviour in C#'s build in [BitConverter](https://docs.microsoft.com/en-us/dotnet/api/system.bitconverter) as well as many other languages. It is misleading for it to return an empty array as that will lead to a length/size of 0, whereas the item still takes up memory space.
> Change Boolean false state

- src/neo-vm/ExecutionContext.cs
- src/neo-vm/ExecutionEngine.cs
- tests/neo-vm.Tests/UtExecutionContext.cs
> Extend ExecutionContext with states

- src/neo-vm/OpCode.cs
PR #91 implemented ability to convert from Array to Struct and vice
versa.
https://github.com/neo-project/neo-vm/pull/91
This PR adds proper doc comments.
> Expand documentation of NEWARRAY and NEWSTRUCT opcodes

- src/neo-vm/ExecutionEngine.cs
- src/neo-vm/OpCode.cs
- src/neo-vm/StackItem.cs
- src/neo-vm/Types/Null.cs
- tests/neo-vm.Tests/Tests/OpCodes/Arrays/APPEND.json
- tests/neo-vm.Tests/Tests/OpCodes/Arrays/PICKITEM.json
- tests/neo-vm.Tests/Tests/OpCodes/Arrays/REMOVE.json
- tests/neo-vm.Tests/Tests/OpCodes/Arrays/SETITEM.json
- tests/neo-vm.Tests/Tests/OpCodes/BitwiseLogic/EQUAL.json
- tests/neo-vm.Tests/Tests/OpCodes/Numeric/NUMEQUAL.json
- tests/neo-vm.Tests/Tests/OpCodes/Numeric/NUMNOTEQUAL.json
- tests/neo-vm.Tests/Tests/OpCodes/Push/PUSHNULL.json
- tests/neo-vm.Tests/Tests/OpCodes/Stack/DUPFROMALTSTACK.json
- tests/neo-vm.Tests/Tests/OpCodes/Stack/DUPFROMALTSTACKBOTTOM.json
- tests/neo-vm.Tests/Tests/OpCodes/Stack/ISNULL.json
- tests/neo-vm.Tests/Tests/OpCodes/Stack/XDROP.json
- tests/neo-vm.Tests/Types/VMUTStackItemType.cs
- tests/neo-vm.Tests/UtStackItem.cs
- tests/neo-vm.Tests/VMJsonTestBase.cs
Related to: https://github.com/neo-project/neo/issues/1112
> Add `PUSHNULL` and `ISNULL`

- .github/workflows/dotnetcore.yml
Because it always fails. We can wait for Github's service to become more stable before enabling it.
> Disable `PublishGithub`

- src/neo-vm/ExecutionEngine.cs
- src/neo-vm/Instruction.cs
- src/neo-vm/OpCode.cs
- src/neo-vm/Types/Pointer.cs
- tests/neo-vm.Tests/Tests/OpCodes/Control/CALLA.json
- tests/neo-vm.Tests/Tests/OpCodes/Push/PUSHA.json
- tests/neo-vm.Tests/Types/VMUTStackItemType.cs
- tests/neo-vm.Tests/VMJsonTestBase.cs
> Implement function pointers

- src/neo-vm/OperandSizeAttribute.cs
This can prevent the duplicate in compiler https://github.com/neo-project/neo-devpack-dotnet/pull/182/files#diff-444cbe5596606ed74000b915750fe568R6
Also it could be useful for parsers.
> Allow to use the OperandSizeAttribute outside neo-vm 

- src/neo-vm/ExecutionContext.SharedStates.cs
- src/neo-vm/ExecutionContext.cs
If `INITSSLOT` is not called in an entry point, the `StaticFields` won't be initialized correctly. This PR fixed it.
> Fixed a bug where StaticFields could not be initialized correctly in non-entry point

- src/neo-vm/Types/Boolean.cs
- src/neo-vm/Types/Buffer.cs
- src/neo-vm/Types/ByteString.cs
- src/neo-vm/Types/CompoundType.cs
- src/neo-vm/Types/Integer.cs
- src/neo-vm/Types/InteropInterface.cs
- src/neo-vm/Types/Null.cs
- src/neo-vm/Types/Pointer.cs
- src/neo-vm/Types/PrimitiveType.cs
- src/neo-vm/Types/StackItem.cs
- src/neo-vm/Types/Struct.cs
- tests/neo-vm.Tests/UtStackItem.cs
> Fix Equal() and GetHashCode()

- tests/neo-vm.Tests/Tests/OpCodes/Control/TRY_CATCH_FINALLY6.json
FAULT state is reached after 2 steps (`TRY` + `ABORT`), there is no need to go further.
I believe if we specify 3 steps in test, we should expect every but last step to finish with success.
> Remove extra step from TRYCATCH test

- src/neo-vm/EvaluationStack.cs
Changes EvaluationStack to implement IReadOnlyList<StackItem> instead of IReadOnlyCollection<StackItem>. IReadOnlyList indexer simply calls existing Peek method.
This change is needed to simplify the trace debugger.
> EvaluationStack implement IReadOnlyList

- src/neo-vm/Types/ByteString.cs
Close https://github.com/neo-project/neo/issues/1855
> Add ByteString.MaxComparableSize

- src/neo-vm/ExecutionEngine.cs
This allow us to configure the `ExecutionContextState` before trigger `protected override void LoadContext(ExecutionContext context)`
> Allow to Create context without load

- src/neo-vm/Types/ByteString.cs
- src/neo-vm/Types/Map.cs
- tests/neo-vm.Tests/Tests/OpCodes/Arrays/HASKEY.json
Map checks if the key it's longer than 64 bytes, but it's possible to bypass this and force to call `GetHashCode` with a 1024*1024 stack item using other opcodes like `HASHKEY`
Proof of Concept:
```csharp
[TestMethod]
public void TestDosByteString()
{
TestBlockchain.InitializeMockNeoSystem();
using var script = new ScriptBuilder();
script.EmitPush(1024 * 1024);
script.Emit(OpCode.NEWBUFFER);
script.Emit(OpCode.NEWMAP);
script.EmitPush(64);
script.Emit(OpCode.NEWBUFFER);
script.Emit(OpCode.INITSLOT, new byte[] { 0, 3 });
script.Emit(OpCode.LDARG1);
script.Emit(OpCode.LDARG0);
script.Emit(OpCode.CONVERT, new byte[] { (byte)StackItemType.ByteString });
script.Emit(OpCode.LDARG0);
script.Emit(OpCode.SETITEM);
script.Emit(OpCode.LDARG1);
script.Emit(OpCode.LDARG2);
script.Emit(OpCode.CONVERT, …
```
> Prevent DoS by GetHashCode

- src/neo-vm/Utility.cs
- tests/neo-vm.Tests/Tests/OpCodes/Arithmetic/SQRT.json
> FIX `SQRT`

- tests/neo-vm.Tests/Tests/OpCodes/Control/TRY_CATCH_FINALLY10.json
See https://github.com/nspcc-dev/neo-go/pull/2396 , C# node behaves correctly.
Signed-off-by: Evgenii Stratonikov <evgenii@nspcc.ru>
> Add a test for ENDFINALLY without ENDTRY

- src/neo-vm.Benchmarks/Benchmarks.cs
- src/neo-vm/ExecutionEngine.cs
- src/neo-vm/ReferenceCounter.cs
- src/neo-vm/Types/Buffer.cs
- src/neo-vm/Types/StackItem.cs
- tests/neo-vm.Tests/VMJsonTestBase.cs
1. Used `ArrayPool` to optimize the performance of `Buffer`.
2. Added a new benchmark: NeoIssue2723. The iteration number is changed to `130000`, which consumes about 10GAS at default settings.
Close neo-project/neo#2723
> Optimize Buffer: uses ArrayPool

- .github/workflows/main.yml
- src/Neo.VM/Collections/OrderedDictionary.cs
- src/Neo.VM/Cryptography/BitOperations.cs
- src/Neo.VM/Instruction.cs
- src/Neo.VM/IsExternalInit.cs
- src/Neo.VM/Neo.VM.csproj
- src/Neo.VM/ReferenceEqualityComparer.cs
- src/Neo.VM/StronglyConnectedComponents/Tarjan.cs
- src/Neo.VM/Types/Buffer.cs
- src/Neo.VM/Types/Map.cs
- src/Neo.VM/Utility.cs
- tests/Neo.VM.Tests/Neo.VM.Tests.csproj
This is an alternative version of #498. That PR uses C# 8.0. This PR uses C# 9.0. Technically, C# 9 is only supported on .NET 5 and later, but Microsoft itself uses approaches from this PR to target older frameworks from C# 9.0. ([Example](https://github.com/dotnet/orleans)).
cc @erikzhang @shargon @igormcoelho 
* in order to support init only properties, Neo.VM needs a local internal copy of `IsExternalInit`. This is a marker class with no code, and is only used by the compiler for tracking metadata.
* .NET 5 is no longer supported, so this PR only targets .NET Standard 2.1 and 6.0
Other changes in this PR that match changes made in #498:
* Implement `BitOperations.RotateLeft`, `ReferenceEqualityComparer` and `BigInteger.GetBitLength` on .NET Standard 2.1 (.NET 6 uses the BCL provided …
> Support .NET Standard 2.1(Take two)

- src/Neo.VM/ExecutionEngine.cs
- src/Neo.VM/OpCode.cs
- tests/Neo.VM.Tests/Tests/OpCodes/Control/ABORTMSG.json
- tests/Neo.VM.Tests/Tests/OpCodes/Control/ASSERTMSG.json
- tests/Neo.VM.Tests/Types/TestEngine.cs
- tests/Neo.VM.Tests/Types/VMUTExecutionEngineState.cs
- tests/Neo.VM.Tests/VMJsonTestBase.cs
See https://github.com/neo-project/neo/issues/2782#issuecomment-1259504674
I think there's a big upside in supporting this in terms of improved developer experience by having actual feedback on why the ABORT or ASSERT failed. Hence why I'm trying to keep this going
For example [the reason(s)](https://github.com/nspcc-dev/neo-go/blob/3dbd36ef70c902ace1552b849a00a454a3fad73b/examples/nft-d/nft.go#L362-L377) why sending funds to this NFT fails can actually be communicated back to the user without having to run a node yourself in order to be able to read the logs
> Add ABORTMSG & ASSERTMSG

- src/Neo.VM/ExecutionEngineLimits.cs
As conversed with @roman-khimov 
Alternative to fix https://github.com/neo-project/neo-vm/pull/512
Max transaction script size is [64Kb](https://github.com/neo-project/neo/blob/f5e257c11c514e47cdc1da6116e475a7324ba1ac/src/Neo/Network/P2P/Payloads/Transaction.cs#L240), has no sense to have a bigger item, the longest one should be a nef file, and it should be limited to the transaction script size ([now is not](https://github.com/neo-project/neo/blob/f5e257c11c514e47cdc1da6116e475a7324ba1ac/src/Neo/SmartContract/Native/ContractManagement.cs#L218C91-L218C98))
> Enhance the limits

- src/Neo.VM/ExecutionContext.cs
- tests/Neo.VM.Tests/UtExecutionContext.cs
Required for https://github.com/neo-project/neo/pull/2942
> Add factory to GetState

- src/Neo.VM/Instruction.cs
- tests/Neo.VM.Tests/UtScript.cs
Close https://github.com/neo-project/neo-vm/issues/517
> Fix Instruction error
