- src/AntShares.Compiler.MSIL/Conv_Multi.cs
- src/AntShares.Compiler.MSIL/ILModule.cs
> fix call stack problem

- src/AntShares.Compiler.MSIL/Conv_Multi.cs
- src/AntShares.Compiler.MSIL/Converter.cs
- src/AntShares.Compiler.MSIL/Program.cs
- src/AntShares.Compiler.MSIL/project.json
> add "string" and "null" support

- src/AntShares.Compiler.MSIL/Conv_Common.cs
- src/AntShares.Compiler.MSIL/Conv_Multi.cs
- src/AntShares.Compiler.MSIL/Converter.cs
- src/AntShares.Compiler.MSIL/ILModule.cs
- src/AntShares.VM/ExecutionEngine.cs
- src/AntShares.VM/OpCode.cs
add support for struct:
like this:
public struct testS
{
public int a;
public string b;
public byte[] c;
}
public static int testStruct()
{
testS s = new testS();
s.a = 55;
return s.a;
}
> add array and struct support for vm and compiler

- src/AntShares.Compiler.MSIL/MSIL/Conv_Multi.cs
- src/AntShares.Compiler.MSIL/MSIL/Converter.cs
2.增加
BigNumber.ToByteArray的解析
和
new BigNumber（byte[])的解析
> support for NonemitAttribute and conversion between BigInteger and byte[]

- src/neo-vm/ExecutionEngine.cs
- src/neo-vm/OpCode.cs
> add new opcode `VERIFY`

- src/neo-vm/OpCode.cs
@erikzhang I documented the opcodes (in English), and many of them were lacking any type of documentation. If you think that's correct, please accept this PR.
> documentation for opcodes in English

- src/neo-vm/ExecutionEngine.cs
- src/neo-vm/Helper.cs
- src/neo-vm/InteropService.cs
This is a proposal for issue https://github.com/neo-project/neo/issues/264, directly on neo-vm.
> hashing interop names to uint32

- src/neo-vm/ExecutionContext.cs
- Exception occurs in debuggers and unit testing
> Prevent exception on last Instruction

- src/neo-vm/OpCode.cs
Proposed documentation for Stack Isolation opcodes.
> Documentation for Stack Isolation

- src/neo-vm/ExecutionEngine.cs
- tests/neo-vm.Tests/Tests/OpCodes/Arrays/PICKITEM.json
- Clean switch code
- Add ut for ByteArray and FAULT
> Clean code and UT

- src/neo-vm/ExecutionEngine.cs
- tests/neo-vm.Tests/Tests/OpCodes/Arrays/PICKITEM.json
> Implement PICKITEM for ByteArray

- src/neo-vm/ExecutionContext.cs
- src/neo-vm/ExecutionEngine.cs
- src/neo-vm/Instruction.cs
- src/neo-vm/OpCode.cs
- tests/neo-vm.Tests/Tests/Others/Debugger.json
> Remove `OpCode.CALL_I`

- src/neo-vm/ExecutionEngine.cs
- src/neo-vm/OpCode.cs
Original Pull request https://github.com/neo-project/neo-vm/pull/153
> Remove SHA opcode

- src/neo-vm/ExecutionContext.cs
- src/neo-vm/Instruction.cs
- src/neo-vm/RandomAccessStack.cs
- src/neo-vm/Script.cs
- src/neo-vm/Types/Array.cs
- src/neo-vm/Types/Boolean.cs
- src/neo-vm/Types/ByteArray.cs
- src/neo-vm/Types/Integer.cs
- src/neo-vm/Types/InteropInterface.cs
- src/neo-vm/Types/Map.cs
- src/neo-vm/Types/Struct.cs
`DebuggerDisplay` Is very useful when debug smart contracts in virtual machine
> DebuggerDisplay

- src/neo-vm/Debugger.cs
- src/neo-vm/ExecutionEngine.cs
Close https://github.com/neo-project/neo-vm/issues/188
> Remove HasFlag calls

- src/neo-vm/ExecutionEngine.cs
Require to test the backward compatibility (with mainnet and testnet)
> Check items after copy an array/struct (2x)

- .github/workflows/dotnetcore.yml
If the version of neo-vm changed, the workflow will automatically create a new release on Github, and then push the package to NuGet.
> Automatically create release

- src/neo-vm/ReferenceCounter.cs
- src/neo-vm/Types/Array.cs
- src/neo-vm/Types/CompoundType.cs
- src/neo-vm/Types/Map.cs
- tests/neo-vm.Tests/UtReferenceCounter.cs
Fixes neo-project/neo-devpack-dotnet#147 https://github.com/neo-project/neo/issues/1330
> Fix ReferenceCounter

- src/neo-vm/ExecutionEngine.cs
- src/neo-vm/Types/Boolean.cs
- src/neo-vm/Types/ByteArray.cs
- src/neo-vm/Types/Integer.cs
- src/neo-vm/Types/PrimitiveType.cs
- src/neo-vm/Types/StackItem.cs
- src/neo-vm/Types/StackItemType.cs
- tests/neo-vm.Tests/Tests/OpCodes/Arrays/HASKEY.json
- tests/neo-vm.Tests/Tests/OpCodes/Arrays/NEWARRAY_T.json
- tests/neo-vm.Tests/Tests/OpCodes/BitwiseLogic/EQUAL.json
- tests/neo-vm.Tests/Tests/OpCodes/BitwiseLogic/NOTEQUAL.json
- tests/neo-vm.Tests/Tests/OpCodes/Numeric/NOT.json
- tests/neo-vm.Tests/Tests/OpCodes/Numeric/NUMEQUAL.json
- tests/neo-vm.Tests/Tests/OpCodes/Numeric/NUMNOTEQUAL.json
- tests/neo-vm.Tests/Tests/OpCodes/Numeric/SIGN.json
- tests/neo-vm.Tests/Tests/OpCodes/Stack/NIP.json
- tests/neo-vm.Tests/Tests/OpCodes/Types/CONVERT.json
- tests/neo-vm.Tests/Tests/OpCodes/Types/ISNULL.json
- tests/neo-vm.Tests/Tests/OpCodes/Types/ISTYPE.json
- tests/neo-vm.Tests/Tests/Others/ScriptLogic.json
- tests/neo-vm.Tests/Tests/Others/StackItemLimits.json
- tests/neo-vm.Tests/Types/VMUTStackItemType.cs
- tests/neo-vm.Tests/UtStackItem.cs
- tests/neo-vm.Tests/VMJsonTestBase.cs
Since we all hesitate in neo-project/neo#1374, we better restore the `Boolean` first, and then move on to other work. Make decisions later when we have a stronger reason.
> Revert "Remove Boolean"

- src/neo-vm/ExecutionEngine.cs
- src/neo-vm/Script.cs
- src/neo-vm/Types/Pointer.cs
- src/neo-vm/Unsafe.cs
- tests/neo-vm.Tests/UtScript.cs
- tests/neo-vm.Tests/UtStackItem.cs
Close https://github.com/neo-project/neo-vm/issues/277
> Add pointer script check

- .github/workflows/dotnetcore.yml
Copy of https://github.com/neo-project/neo-modules/pull/185
> Fix dotnet-format

- src/neo-vm/ExecutionEngine.cs
> Change PUSHA to be relative

- src/neo-vm/ExecutionContext.cs
- src/neo-vm/ExecutionEngine.cs
- tests/neo-vm.Tests/UtExecutionContext.cs
It will be required for https://github.com/neo-project/neo/pull/1629
> Change ExecutionContext.Clone to public

- src/neo-vm/ExecutionEngine.cs
> Add OnStateChanged()

- src/neo-vm/ExecutionContext.cs
- src/neo-vm/ExecutionEngine.cs
- tests/neo-vm.Tests/UtExecutionContext.cs
> Remove RVCount

- .github/workflows/dotnetcore.yml
Apply https://github.com/neo-project/neo/pull/1775
> workflows: use checkout action v2

- src/neo-vm/Collections/OrderedDictionary.cs
Remove two searches in the internal collection
> Optimize OrderedDictionary

- src/neo-vm/Types/ByteString.cs
- tests/neo-vm.Tests/Tests/Others/StackItemLimits.json
Close https://github.com/neo-project/neo-vm/issues/348
> Change ByteString.GetBoolean when the size it's bigger than expected

- src/neo-vm/ExecutionEngine.cs
> Make ExecutionEngine.Execute method virtual

- src/neo-vm/ExecutionEngine.cs
- src/neo-vm/UnhandledException.cs
- src/neo-vm/VMUnhandledException.cs
> Add UnhandledException

- src/neo-vm/ExecutionEngine.cs
> Add MaxTryNestingDepth

- src/neo-vm/ExecutionEngine.cs
- src/neo-vm/OpCode.cs
> Add new opcode POPITEM

- src/neo-vm/EvaluationStack.cs
- src/neo-vm/ExecutionEngine.cs
- src/neo-vm/Instruction.cs
- src/neo-vm/ReferenceCounter.cs
- src/neo-vm/Types/ByteString.cs
- src/neo-vm/Types/Integer.cs
- src/neo-vm/Types/InteropInterface.cs
- src/neo-vm/Types/Map.cs
- src/neo-vm/Types/Null.cs
- src/neo-vm/Types/PrimitiveType.cs
- src/neo-vm/Types/Struct.cs
- tests/neo-vm.Tests/UtStackItem.cs
- tests/neo-vm.Tests/UtStruct.cs
- tests/neo-vm.Tests/UtUnsafe.cs
While changing the compiler I have missed some detail in certain exceptions
> Add some exception messages

- src/neo-vm/Types/Map.cs
Related to https://github.com/neo-project/neo-vm/pull/393#issuecomment-771519405
> Add one more key size check

- src/neo-vm/ReferenceCounter.cs
- src/neo-vm/Slot.cs
- Remove Linq query
- Optimize Reference adition
> Optimize Slot constructor

- src/neo-vm/ExecutionEngine.cs
- src/neo-vm/OpCode.cs
- src/neo-vm/Utility.cs
- tests/neo-vm.Tests/Tests/OpCodes/Numeric/POW.json
- tests/neo-vm.Tests/Tests/OpCodes/Numeric/SQRT.json
Close https://github.com/neo-project/neo/issues/2357
> Add POW and SQRT

- src/neo-vm/Collections/OrderedDictionary.cs
- src/neo-vm/Debugger.cs
- src/neo-vm/EvaluationStack.cs
- src/neo-vm/ExecutionEngine.cs
- src/neo-vm/ExecutionEngineLimits.cs
- src/neo-vm/GlobalSuppressions.cs
- src/neo-vm/ReferenceCounter.cs
- src/neo-vm/Script.cs
- src/neo-vm/ScriptBuilder.cs
- src/neo-vm/Types/Buffer.cs
- src/neo-vm/Types/Map.cs
- src/neo-vm/Types/Struct.cs
- src/neo-vm/VMUnhandledException.cs
- tests/neo-vm.Tests/Extensions/StringExtensions.cs
- tests/neo-vm.Tests/Helpers/RandomHelper.cs
- tests/neo-vm.Tests/UtDebugger.cs
- tests/neo-vm.Tests/UtEvaluationStack.cs
- tests/neo-vm.Tests/UtReferenceCounter.cs
- tests/neo-vm.Tests/UtScriptBuilder.cs
- tests/neo-vm.Tests/UtSlot.cs
- tests/neo-vm.Tests/UtStackItem.cs
- tests/neo-vm.Tests/UtStruct.cs
- tests/neo-vm.Tests/VMJsonTestBase.cs
> Apply codding style

- src/neo-vm/ScriptBuilder.cs
- tests/neo-vm.Tests/UtScriptBuilder.cs
> Fix push negative numbers with ScriptBuilder

- src/neo-vm/ReferenceCounter.cs
> Reference counter optimization

- src/neo-vm/ExecutionEngine.cs
- src/neo-vm/Types/StackItem.cs
- src/neo-vm/Types/Struct.cs
- tests/neo-vm.Tests/UtStackItem.cs
- tests/neo-vm.Tests/UtStruct.cs
Close https://github.com/neo-project/neo-vm/issues/426
> struct equal limit

- src/neo-vm/Instruction.cs
- tests/neo-vm.Tests/Tests/OpCodes/Push/PUSHDATA4.json
> Fix  PUSHDATA4

- src/neo-vm/ExecutionEngine.cs
- src/neo-vm/OpCode.cs
- tests/neo-vm.Tests/Tests/OpCodes/Arrays/PACKMAP.json
- tests/neo-vm.Tests/Tests/OpCodes/Arrays/PACKSTRUCT.json
- tests/neo-vm.Tests/Tests/OpCodes/Arrays/UNPACK.json
Close https://github.com/neo-project/neo-vm/issues/442
> add opcodes: PACKSTRUCT, PACKMAP

- src/neo-vm/ScriptBuilder.cs
- tests/neo-vm.Tests/UtScriptBuilder.cs
Close https://github.com/neo-project/neo-vm/issues/451
> Add script builder method

- src/neo-vm/ExecutionEngine.cs
- src/neo-vm/OpCode.cs
- src/neo-vm/Utility.cs
- tests/neo-vm.Tests/Tests/OpCodes/Arithmetic/MODMUL.json
- tests/neo-vm.Tests/Tests/OpCodes/Arithmetic/MODPOW.json
- tests/neo-vm.Tests/UtUtility.cs
> Add new opcodes: MODMUL and MODPOW

- src/neo-vm/OpCode.cs
Close https://github.com/neo-project/neo-vm/issues/445
> Update UNPACK summary

- src/neo-vm/ReferenceCounter.cs
- src/neo-vm/Slot.cs
- src/neo-vm/StronglyConnectedComponents/Tarjan.cs
- src/neo-vm/StronglyConnectedComponents/Vertex.cs
Use [Tarjan's strongly connected components algorithm](https://en.wikipedia.org/wiki/Tarjan's_strongly_connected_components_algorithm).
> Better ReferenceCounter

- tests/neo-vm.Tests/UtScript.cs
Restore ut from https://github.com/neo-project/neo-vm/pull/466/files
> Revert remove UT

- src/Neo.VM/Types/StackItem.cs
Fix https://github.com/neo-project/neo-vm/issues/477
Close https://github.com/neo-project/neo-vm/pull/479
According to https://github.com/neo-project/neo-vm/pull/478#issuecomment-1149883719
> Thread safe static items (v2)

- src/Neo.VM/Types/Buffer.cs
- src/Neo.VM/Types/ByteString.cs
Copy some improves from https://github.com/neo-project/neo-vm/pull/482
> Optimize DebuggerDisplay

- src/Neo.VM/ReferenceCounter.cs
> Track CompoundType and Buffer only

- src/Neo.VM/ExecutionContext.cs
- src/Neo.VM/ExecutionEngine.cs
- src/Neo.VM/Script.cs
- tests/Neo.VM.Tests/UtDebugger.cs
- tests/Neo.VM.Tests/UtScript.cs
> Disallow out-of-bounds method

- src/Neo.VM/ScriptBuilder.cs
- tests/Neo.VM.Tests/UtScriptBuilder.cs
> Fix scriptbuilder EmitPush(bool)

- .github/workflows/main.yml
- benchmarks/Neo.VM.Benchmarks/Neo.VM.Benchmarks.csproj
- src/Neo.VM/Neo.VM.csproj
- tests/Neo.VM.Tests/Neo.VM.Tests.csproj
> update to net7.0

- README.md
People are likely to find this repo and we better have some directions for them.
> README: add archival notice
